use_frameworks!

def anon
  pod 'Anon/GeoIP',
    :path => '../'
#    :podspec => '../AnonStatic.podspec'
end


target 'Tor-Example' do
  platform :ios, '12.0'

  anon

  target 'Tor-Tests' do
    inherit! :search_paths
  end

end

target 'Tor-Example-Mac' do
  platform :macos, '10.13'

  anon
end
